# Generated by Django 2.1.4 on 2019-01-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0017_auto_20190101_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apiresponse',
            field=models.TextField(null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresponse',
            field=models.TextField(null=True, verbose_name='响应数据'),
        ),
    ]
