# Generated by Django 2.1.4 on 2019-01-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0018_auto_20190105_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apiresponse',
            field=models.TextField(blank=True, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apitester',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='测试负责人'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresponse',
            field=models.TextField(blank=True, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestdesc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitester',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='测试负责人'),
        ),
    ]
